### PR TITLE
Reduce namespace pollution by only importing specific functions.

### PR DESCRIPTION
**Pull request by ghost**
looks cleaner and is python 3.5 cmpatible.

if TestProgram is renamed then it would be even better.

### CODE REVIEW

**Comment by dash0002** [comment]
Looks good.  Can you update the README.md (adding your name to contributors) and CHANGLOG.md (adding the changes).  I can test and merge pretty quickly afterwards.

**Comment by ghost** [comment]
Done. tested on my side and it works pretty well.

PS : with verbose < 1 the output is pretty sparse. maybe we could add total, passed and failed statistics to the results. Irrespective of verbosity  ?

**Comment by ghost** [comment]
PPS: the output has the F's printed for failure and seems pretty unnecessary..

**Comment by dash0002** [comment]
Thanks for running test_HTMLTestRunner.py.  Most people aren't and I think that's key for ensuring that HTMLTestRunner.py stays "semi" backward compatible. 
- Are the changes backward compatible within Python 3?  Just looking at them I think so, but didn't have a double check against newest Python features.  I can merge after you can confirm/double check this as I think the branch is ready.
- Agreed on the verbosity.  It would be better to ensure verbose gives a level of detail that is very helpful. 
- Disagreed on the "F's printed".  I think having that quick indicator to the screen is useful and easy to disregard if not necessary. I know many a time, I've sat watching the test run looking for no  F's

**Comment by ghost** [comment]
the changes are 3 compatible (I think so based on the api documentation) and 2.7 backward compatible too(2.7 compatibility I checked). Just need to check if this code will run on 2.7 if print_function is imported from future and based on version import StringIO from io or from StringIO.

Will check that now and revert back on this thread.

About the F just an F is a quick indicator of whether there is a failure but maybe a counter would be of better use.

PS: ment to say a statistics of sorts.

total tests run, passed tests and failed tests

the errors are already there on the html document.

**Comment by ghost** [comment]
Another point that is stuck with me.

Is the stderr and stdout redirection still needed ?

It seems unessary. Testcases that I have written(basic tests with assertEqual) work fine and I get the correct report after removing the output and error stream redirection support.

**Pull request merged**
